# Generated by Django 3.2.9 on 2022-10-06 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ebook',
            old_name='cvr_urls',
            new_name='cover_urls',
        ),
    ]
