# Generated by Django 3.2.9 on 2022-11-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_cvr_urls_ebook_cover_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('price', models.FloatField(null=True)),
            ],
        ),
    ]
